// react-app/src/Form.js
import React from 'react';
import { Link } from 'react-router-dom';

class Form extends React.Component {

  render() {
    return (
      <main role="main" className="flex-shrink-0">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h2>Inclusão de pessoa</h2>
              <form id="dadosForm" noValidate>
                <input type="hidden" name="id" value="" />
                <div className="form-group row">
                  <label className="col-2 col-form-label">Nome completo</label>
                  <div className="col-10">
                    <input type="text" className="form-control" required id="nome" name="nome" value="" />
                  </div>
                </div>
                <div className="form-group row">
                  <label className="col-2 col-form-label">Sexo</label>
                  <div className="col-sm-10">
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="radio" id="sexoF" value="0" name="sexo" checked="checked" />
                      <label className="form-check-label" htmlFor="sexoF">Feminino</label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="radio" id="sexoM" value="1" name="sexo" />
                      <label className="form-check-label" htmlFor="sexoM">Masculino</label>
                    </div>
                  </div>
                </div>
                <div className="form-group row">
                  <label className="col-2 col-form-label">Data nascimento</label>
                  <div className="col-10">
                    <input type="date" className="form-control" required id="dataNascimento" name="dataNascimento" value="" />

                  </div>
                </div>
                <div className="form-group row">
                  <label className="col-2 col-form-label">Interesses</label>
                  <div className="col-sm-10">
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="checkbox" id="interesse_1" value="1" name="interessesId" />
                      <label className="form-check-label" htmlFor="interesse_1">Tecnologia</label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="checkbox" id="interesse_2" value="2" name="interessesId" />
                      <label className="form-check-label" htmlFor="interesse_2">Gastronomia</label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="checkbox" id="interesse_3" value="3" name="interessesId" />
                      <label className="form-check-label" htmlFor="interesse_3">Viagens</label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="checkbox" id="interesse_4" value="4" name="interessesId" />
                      <label className="form-check-label" htmlFor="interesse_4">Investimentos</label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input className="form-check-input" type="checkbox" id="interesse_5" value="5" name="interessesId" />
                      <label className="form-check-label" htmlFor="interesse_5">Esportes</label>
                    </div>
                  </div>
                </div>
                <div className="text-center">
                  <Link to="/" className="btn btn-light">Voltar</Link>
                  <button type="submit" className="btn btn-primary">Salvar</button>
                </div>
              </form>

            </div>
          </div>
        </div>
      </main>
    );
  }
}

export default Form;

// angular-app/src/app/form/form.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { PessoaService } from '../pessoa.service';
import { InteresseService } from '../interesse.service'
import { Pessoa } from '../pessoa';
import { Interesse } from '../interesse';

@Component({ // <-- Essa expressão chama-se "DECORATOR"
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent implements OnInit {

  titulo : string = 'Inclusão de pessoas';
  id: number = null;
  pessoa : Pessoa = {
    nome: '',
    sexo: 0,
    dataNascimento: null,
    interessesId: []
  };
  interesses: Interesse[] = [];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private pessoaService : PessoaService,
    private interesseService : InteresseService
  ) { }

  ngOnInit(): void {
    this.getInteresses();

    this.route.paramMap.subscribe(params => {
      if (params.get('id')) {
        this.id = Number(params.get('id'));
        this.titulo = 'Editar pessoa';
        this.getPessoaById(this.id);
      }
    });
  }

  getPessoaById(id: number) {
    this.pessoaService.getById(id)
      .subscribe(pessoa => {
        this.pessoa = pessoa
        for (let interesse of this.interesses) {
          for (let interesseSelecionado of this.pessoa.interessesId) {
            if (interesse.id === interesseSelecionado) {
              interesse.selecionado = true;
              break;
            }
          }
        }
      }
    );
  }

  getInteresses() {
    this.interesseService.getInteresses()
      .subscribe(interesses => {
        this.interesses = interesses;
        for (let interesse of this.interesses) {
          interesse.selecionado = false;
        }
      }
    );
  }

  onSubmit() {
    let interessesId = [];
    for (const interesse of this.interesses) {
      if (interesse.selecionado) {
        interessesId.push(interesse.id);
      }
    }
    this.pessoa.interessesId = interessesId;
    console.log('**** Dados enviados: ' + JSON.stringify(this.pessoa));
    this.pessoaService.addNew(this.pessoa).subscribe(() => {
      this.router.navigate(['/']);
    });
  }

}

<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Inclusão de pessoa</h2>
      <form id="dadosForm" #form="ngForm" (ngSubmit)="onSubmit()" novalidate>
        <div class="form-group row">
          <label class="col-2 col-form-label">Nome completo</label>
          <div class="col-10">
            <input type="text" class="form-control" required id="nome" name="nome" [(ngModel)]="pessoa.nome">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-2 col-form-label">Sexo</label>
          <div class="col-sm-10">
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" id="sexoF" name="sexo" [value]="0" [(ngModel)]="pessoa.sexo"
                [checked]="pessoa.sexo === 0">
              <label class="form-check-label" for="sexoF">Feminino</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" id="sexoM" name="sexo" [value]="1" [(ngModel)]="pessoa.sexo"
                [checked]="pessoa.sexo === 1">
              <label class="form-check-label" for="sexoM">Masculino</label>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-2 col-form-label">Data nascimento</label>
          <div class="col-10">
            <input type="date" class="form-control" required id="dataNascimento" name="dataNascimento"
              [(ngModel)]="pessoa.dataNascimento">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-2 col-form-label">Interesses</label>
          <div class="col-sm-10" id="interesses">
            <div class="form-check form-check-inline" *ngFor="let interesse of interesses">
              <input class="form-check-input" type="checkbox" name="interessesId" [id]="'interesse_' + interesse.id"
                [checked]="interesse.selecionado" (change)="interesse.selecionado=!interesse.selecionado">
              <label class="form-check-label" [attr.for]="'interesse_' + interesse.id">{{interesse.nome}}</label>
            </div>
          </div>
        </div>
        <div class="text-center">
          <a routerLink="/" class="btn btn-light">Voltar</a>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </form>
      <div>{{interesses | json}}</div>
      <div>{{pessoa | json}}</div>
    </div>
  </div>
</div>
