// angular-app/src/app/lista/lista.component.ts
import { Component, OnInit } from '@angular/core';
import { PessoaService } from '../pessoa.service';
import { Pessoa } from '../pessoa'

@Component({ // <-- Essa expressão chama-se "DECORATOR"
  selector: 'app-lista',
  templateUrl: './lista.component.html',
  styleUrls: ['./lista.component.css']
})
export class ListaComponent implements OnInit {

  pessoas : Pessoa[] = [
    {
      id: 1,
      nome: 'João da Silva',
      sexo: 1,
      dataNascimento: new Date('2000-01-01'),
      interessesId: [1, 2]
    },
    {
      id: 2,
      nome: 'Maria de Souza',
      sexo: 0,
      dataNascimento: new Date('2000-02-02'),
      interessesId: [2, 5]
    },
    {
      id: 3,
      nome: 'José dos Santos',
      sexo: 1,
      dataNascimento: new Date('2000-03-25'),
      interessesId: [2, 5]
    }
  ];
  paginaAtual: number = 0;
  ultimaPagina: number = 0;
  qtd: number = 10;
  first: boolean = true;
  last: boolean = true;

  constructor(private pessoaService : PessoaService) { }

  ngOnInit(): void {
    this.listar();
  }

  listar(): void {
    this.pessoaService.getPagedResult(this.paginaAtual, this.qtd).subscribe(resultado => {
      this.pessoas = resultado.content;
      this.paginaAtual = resultado.number;
      this.ultimaPagina = resultado.totalPages - 1;
      this.first = resultado.first;
      this.last = resultado.last;
    });
  }

  hasPaginaAnterior(): boolean {
    return (this.paginaAtual - 1) >= 0;
  }

  hasProximaPagina(): boolean {
    return (this.paginaAtual + 1) <= this.ultimaPagina;
  }

  goPaginaAnterior(ev: any): void {
    ev.preventDefault();
    if (this.hasPaginaAnterior) {
      this.paginaAtual--;
      this.listar();
    }
  }

  goProximaPagina(ev: any): void {
    ev.preventDefault();
    if (this.hasProximaPagina) {
      this.paginaAtual++;
      this.listar();
    }
  }

  goPrimeiraPagina(ev: any): void {
    ev.preventDefault();
    this.paginaAtual = 0;
    this.listar();
  }

  goUltimaPagina(ev: any): void {
    ev.preventDefault();
    this.paginaAtual = this.ultimaPagina;
    this.listar();
  }

}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>Pessoas - Angular</h2>
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Data nascimento</th>
                        <th>AÇÕES</th>
                    </tr>
                </thead>
                <tbody id="itensTabela">
                    <tr *ngFor="let pessoa of pessoas">
                        <td>{{pessoa.id}}</td>
                        <td>{{pessoa.nome}}</td>
                        <td>{{pessoa.dataNascimento}}</td>
                        <td>
                            <button class="btn btn-primary" [routerLink]="['/editar', pessoa.id]"><i class="fa fa-pencil"></i></button>
                            <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" style="text-align: right">
                            <nav aria-label="Paginação">
                                <ul class="pagination">
                                    <li class="page-item" [ngClass]="{'disabled' : first}">
                                        <a class="page-link" href="#" id="pageFirst" (click)="goPrimeiraPagina($event)">Primeiro</a>
                                    </li>
                                    <li class="page-item" *ngIf="hasPaginaAnterior()">
                                        <a class="page-link" href="#" id="pagePrevious" (click)="goPaginaAnterior($event)">{{paginaAtual}}</a>
                                    </li>
                                    <li class="page-item active">
                                        <a class="page-link active" href="#"><span
                                                id="pageCurrentText">{{paginaAtual + 1}}</span><span
                                                class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="page-item" *ngIf="hasProximaPagina()">
                                        <a class="page-link" href="#" id="pageNext" (click)="goProximaPagina($event)">{{paginaAtual + 2}}</a>
                                    </li>
                                    <li class="page-item" [ngClass]="{'disabled' : last}">
                                        <a class="page-link" href="#" id="pageLast" (click)="goUltimaPagina($event)">Último</a>
                                    </li>
                                </ul>
                            </nav>
                        </td>
                    </tr>
                </tfoot>
            </table>
            <a routerLink="/novo" class="btn btn-success"><i class="fa fa-plus-circle"></i> Incluir novo</a>
            <div id="modalDelete" class="modal fade" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <header class="modal-header">
                            <h5>Confirmar remoção</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                <span aria-hidden="true">X</span>
                            </button>
                        </header>
                        <div class="modal-body">
                            <p class="modal-message">Confirma remoção?</p>
                        </div>
                        <footer class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                            <form style="display: inline-block" method="post">
                                <button type="submit" class="btn btn-danger">Sim</button>
                            </form>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// react-app/src/Lista.js
import React from 'react';
import { Link } from 'react-router-dom'

const TableBody = props => {
  const rows = props.data.map(function(row, index) {
    return (
      <tr key={index}>
        <td>{row.id}</td>
        <td>{row.nome}</td>
        <td>{row.dataNascimento}</td>
        <td>
          <Link to={"/edit/" + row.id} className="btn btn-primary"><i class="fa fa-pencil"></i></Link>
          <a href="#" class="btn btn-danger"><i class="fa fa-trash"></i></a>
        </td>
      </tr>
    )
  });
  return <tbody>{rows}</tbody>
}

class Lista extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      data: {
        content: [
          {
            id: 1,
            nome: "João da Silva",
            dataNascimento: "2000-01-01"
          },
          {
            id: 2,
            nome: "Maria de Souza",
            dataNascimento: "2000-02-20"
          },
          {
            id: 3,
            nome: "José dos Santos",
            dataNascimento: "2000-03-25"
          }
        ],
        number: 0,
        totalPages: 99,
        first: true,
        last: false,

      },
      paginaAtual: 0,
      ultimaPagina: 0,
      qtd: 10
    }
  }

  loadData(page) {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", "http://localhost:8080/rest/pessoas?pagina=" + page + "&qtd=" + this.state.qtd, true);
    const component = this;
    xhr.addEventListener("load", function() {
      if (xhr.status >= 200 && xhr.status < 400) {
        let data = JSON.parse(xhr.responseText);
        component.setState({
          data: data,
          paginaAtual: data.number,
          ultimaPagina: data.totalPages - 1
        });
      }
    });
    xhr.send();
  }

  componentDidMount() {
    this.loadData(this.state.paginaAtual);
  }

  render() {
    return (
      <main role="main" className="flex-shrink-0">
      <div className="container">
        <div className="row">
          <div className="col-12">
            <h2>Pessoas - React App</h2>
            <table className="table table-striped">
              <thead className="thead-dark">
                <tr>
                  <th>ID</th>
                  <th>Nome</th>
                  <th>Data nascimento</th>
                  <th>AÇÕES</th>
                </tr>
              </thead>
              <TableBody data={this.state.data.content} />
              <tfoot>
                <tr>
                  <td colSpan="4" style={{textAlign: 'right'}}>
                    <nav aria-label="Paginação">
                      <ul className="pagination">
                        <li className={"page-item " + (this.state.data.first ? "disabled" : "")}>
                          <a className="page-link" href="#" >Primeiro</a>
                        </li>
                        {
                          this.state.data.number - 1 > 0 &&
                          <li className="page-item">
                            <a className="page-link" href="#">{this.state.data.number}</a>
                          </li>
                        }
                        <li className="page-item active">
                          <a className="page-link active" href="#">{this.state.data.number + 1}<span className="sr-only">(current)</span></a>
                        </li>
                        {
                          this.state.data.number + 1 < this.state.data.totalPages &&
                          <li className="page-item">
                            <a className="page-link" href="#">{this.state.data.number + 2}</a>
                          </li>
                        }
                        <li className={"page-item " + (this.state.data.last ? "disabled" : "")}>
                          <a className="page-link" href="#">Último</a>
                        </li>
                      </ul>
                    </nav>
                  </td>
                </tr>
              </tfoot>
            </table>
            <Link to="/new" className="btn btn-success"><i className="fa fa-plus-circle"></i> Incluir novo</Link>
            <div id="modalDelete" className="modal fade" tabIndex="-1" role="dialog">
              <div className="modal-dialog" role="document">
                <div className="modal-content">
                  <header className="modal-header">
                    <h5>Confirmar remoção</h5>
                    <button type="button" className="close" data-dismiss="modal" aria-label="Fechar">
                      <span aria-hidden="true">X</span>
                    </button>
                  </header>
                  <div className="modal-body">
                    <p className="modal-message">Confirma remoção?</p>
                  </div>
                  <footer className="modal-footer">
                    <button type="button" className="btn btn-secondary" data-dismiss="modal">Não</button>
                    <form style={{display: 'inline-block'}} method="post">
                      <button type="submit" className="btn btn-danger">Sim</button>
                    </form>
                  </footer>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    );
  }
}

export default Lista;
